on:
    push:
      branches:
        - main
jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          id: checkout_repo
          uses: actions/checkout@v3
        - name: do_go_mod_tidy
          run: go mod tidy
        - name: Run Unit tests
          run: |
            go test -race -covermode atomic -coverprofile=covprofile ./...
        - name: Install goveralls
          run: go install github.com/mattn/goveralls@latest
        - name: Send coverage
          env:
            COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
          run: goveralls -coverprofile=covprofile -service=github